(* This is free and unencumbered software released into the public domain. *)

(* See: https://github.com/weavery/clarity.js#supported-clarity-features *)

let is_primitive = function
  | "*" | "mul"
  | "+" | "add"
  | "-" | "sub"
  | "/" | "div"
  | "<" | "lt"
  | "<=" | "le"
  | ">" | "gt"
  | ">=" | "ge"
  | "append"
  | "as-contract"
  | "as-max-len?"
  | "at-block"
  | "block-height"
  | "burn-block-height"
  | "concat"
  | "contract-call?"
  | "contract-caller"
  | "contract-of"
  | "default-to"
  | "err"
  | "filter"
  | "fold"
  | "ft-get-balance"
  | "ft-mint?"
  | "ft-transfer?"
  | "get"
  | "get-block-info?"
  | "hash160"
  | "is-eq"
  | "is-err"
  | "is-in-regtest"
  | "is-none"
  | "is-ok"
  | "is-some"
  | "keccak256"
  | "len"
  | "list"
  | "map"
  | "map-delete"
  | "map-get?"
  | "map-insert"
  | "map-set"
  | "mod"
  | "nft-get-owner?"
  | "nft-mint?"
  | "nft-transfer?"
  | "none"
  | "not"
  | "ok"
  | "pow"
  | "print"
  | "sha256"
  | "sha512"
  | "sha512/256"
  | "some"
  | "stx-liquid-supply"
  | "to-int"
  | "to-uint"
  | "try!"
  | "tuple"
  | "tx-sender"
  | "unwrap!"
  | "unwrap-err!"
  | "unwrap-err-panic"
  | "unwrap-panic"
  | "xor" -> true
  | _ -> false
